language: cpp

compiler:
  - gcc

before_script:
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq help2man

script: autoreconf -vfi && ./configure && make && make check

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - sweet_f_a@gmx.de
