language: cpp

sudo: required

compiler:
  - gcc
  - clang

env:
  - CONFOPTS=""
  - CONFOPTS="--disable-fast-printing"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: TRUSTY="yes"
           CONFOPTS=""
    - os: osx
      compiler: gcc
      env: CONFOPTS=""
    - os: osx
      compiler: clang
      env: CONFOPTS=""
    - os: linux
      compiler: gcc
      env: BUILD_MINGW="yes"
           CONFOPTS="--host=i586-mingw32msvc"
    - os: linux
      compiler: clang
      env: BUILD_MINGW="yes"
           CONFOPTS="--host=i586-mingw32msvc --disable-fast-printing"

install:
  - env
  - source ./.travis-functions.sh
  - travis_have_sudo
  - travis_install_script

before_script:
  - travis_before_script

script:
  - travis_script

branches:
  only:
    - master
    - next
    - /^travis.*/
    - /^tmp.*/
